### PR TITLE
Add MongoKitten

### PR DESCRIPTION
**Pull request by finestructure**

### CODE REVIEW

**Comment by finestructure** [comment]
Acceptance posted: https://forums.swift.org/t/sswg-0027-mongokitten/69249/6

**Review by ktoso — APPROVED** [review]
Lgtm!

**Review by KidiIT — COMMENTED** [review]
All reviewed and approved🫶❤️

**Review by KidiIT — COMMENTED** [review]
All reviewed✅

**Comment by KidiIT** [comment]
All checked out✔️✔️

**Review by KidiIT — COMMENTED** [review]
All new features are available and has been updated to the latest version of the app and will continue for updates on future updates and improvements in iOS development as the game develops in a more robust manner and more user friendly experience for all platforms and devices🥰🙌❤️

**Pull request merged**
