### PR TITLE
Add Vapor and Hummingbird

### PR DESCRIPTION
**Pull request by 0xTim**

### CODE REVIEW

**Review by finestructure — APPROVED** [review]

**Review by adam-fowler — APPROVED** [review]

**Comment by 0xTim** [comment]
@yim-lee how do we trigger CI in this repo?

**Comment by yim-lee** [comment]
@swift-server-bot add to allowlist

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
CI seems to be in a bad state. Will need to take a look.

**Comment by adam-fowler** [comment]
> CI seems to be in a bad state. Will need to take a look.

Yeah I've been trying to merge a PR in https://github.com/swift-server/swiftly this weekend and the CI is failing in odd ways. Wasn't sure if it is the CI or PR.

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Pull request merged**
