### PR TITLE
update docker to use focal + 5.5

### PR DESCRIPTION
**Pull request by tomerd**
generator now requires 5.5

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Review by yim-lee — APPROVED** [review]
LGTM

This fixes the generator build: https://github.com/apple/swift-package-collection-generator/pull/42

**Comment by yim-lee** [comment]
I created 5.6 branch as well:
https://github.com/apple/swift-package-collection-generator/tree/5.6

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Pull request merged**
